### ISSUE TITLE
Not saved configuration.

### ISSUE THREAD

**Issue by wmeneses** [DonutsNL/glpisaml#11]
Thank you for continuing this project,

I have tried to test it but when I save I get this error
"Error: Unable to add new GlpiSaml configuration!!!
Leaving a line without text in the configuration, any suggestions?

**Comment by l-2-m** [comment]
Hi I have the same problem

**Comment by DonutsNL** [comment]
be aware that this version is still being developed. Please add screenshots showing the error for my understanding.

If you need a functioning version. Please use the phpsaml repo.

Rgrds,

**Comment by wmeneses** [comment]
> be aware that this version is still being developed. If you are testing m, thanks for helping 👍🏻Please add screenshots showing the error for my understanding.
> 
> If you need a functioning version. Please use the phpsaml repo.
> 
> Rgrds,

Thanks, I tried the phpsaml version and now it works fine.

**Comment by DonutsNL** [comment]
The ConfigEntity object was normalizing the configuration. As a result the `ID`, `CREATE_DATE`, and `MOD_DATE` fields where passed as NULL to the COMMONDBTM object for insertion. This is invalid because the config doesnt exist yet and we are relying on the database its AUTO_INCREMENT, and DEFAULT CURRENT_TIMESTAMP functions to auto fill these required fields on first insertion. I modified the SamlConfig->getFieldsForDB() to ignore provided fields and filter them out.

![image](https://github.com/DonutsNL/glpisaml/assets/97617761/91312f50-c00c-4b20-a5fd-f23958b33f74)

Tested insertion of new configurations and it now works as expected.
