### ISSUE TITLE
Configuration line not displayed

### ISSUE THREAD

**Issue by Loopers29** [DonutsNL/glpisaml#9]
Hello @DonutsNL,

Thank you for this v2.
However I have a problem, once I've created my SSO configuration, I can't go back to it because I can't click anywhere because the name is not displayed :
<img width="1260" alt="Screenshot 2024-02-29 at 10 37 02" src="https://github.com/DonutsNL/glpisaml/assets/55393114/1b6608c8-b5cc-4181-98d2-c1c320a745b1">

I'm using version 10.0.12.

**Comment by DonutsNL** [comment]
Hi Loopers,

Thank you for reporting this issue. **Be aware that glpisaml is very much a work in progress.** It is not yet usable or production ready because the whole login flow still needs to be implemented. If you are testing it, then i am most greatfull. Need a working version, then Please use phpsaml in my repository in the meantime. 

Could you also share the logging in GLPI_HOME/files/_log/php_error.log?

Thanks in advance.

**Comment by DonutsNL** [comment]
Updated glpi to version 10.0.12. And I cant replicate this issue.

Because there is no logging, there is no way to know whats going on.
